### ISSUE TITLE
Submit new request

### ISSUE THREAD

**Issue by kalanialdrich** [IAmTheElliot/GoodFellows_GoodSamaritan#8]
I want to submit a new request

**Comment by IAmTheElliot** [comment]
Requestor ID
Description
IsActive(boolean)
Date

**Comment by IAmTheElliot** [comment]
framework is started, needs to be completed:
button.on(click) at bottom of app.js needs to point to correct event.
createrequest push needs requestorID filled
createrequest push needs firebase callback function added, if necessary

**Comment by IAmTheElliot** [comment]
submit new request implemented with on.click method.
fixed the jquery button name
points to userRequest.createRequest prototype
checks for blank text field before submitting new request
